/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bankaccounts.ui;

import com.mycompany.bankaccounts.User.User;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author marl8n
 */
public class frame extends javax.swing.JFrame {

    
    ArrayList<User> accounts = new ArrayList<User>();
    int c;
    
    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(opDepositRadioButton);
        buttonGroup.add(opRetireRadioButton);
        buttonGroup.add(opConsultAccountBalanceRadioButton);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addDpiTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addBalanceTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        opDepositRadioButton = new javax.swing.JRadioButton();
        opRetireRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        opDpiTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        opAmountTextField = new javax.swing.JTextField();
        opButton = new javax.swing.JButton();
        showUsers = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        opConsultAccountBalanceRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DPI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Saldo");

        addButton.setText("Agregar");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        jLabel4.setText("Deposito/Retiro");

        opDepositRadioButton.setText("Deposito");

        opRetireRadioButton.setText("Retiro");

        jLabel5.setText("DPi");

        jLabel6.setText("Monto");

        opButton.setText("Hacer Operacion");
        opButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opButtonMouseClicked(evt);
            }
        });

        showUsers.setText("Mostrar Cuentas");
        showUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showUsersMouseClicked(evt);
            }
        });

        opConsultAccountBalanceRadioButton.setText("Consultar Saldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addDpiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(opAmountTextField)
                                            .addComponent(opDpiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(opButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(showUsers))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(opDepositRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opRetireRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opConsultAccountBalanceRadioButton)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addDpiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(addNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(addBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opDepositRadioButton)
                    .addComponent(opRetireRadioButton)
                    .addComponent(opConsultAccountBalanceRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(opDpiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(opAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showUsers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        addAccount();
        JOptionPane.showMessageDialog(rootPane, "Operacion Realizada con Exito\n"+ accounts.get(c-1).getName()
                        + "Saldo actual: " + accounts.get(c-1).getBalance());
    }//GEN-LAST:event_addButtonMouseClicked

    private void opButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opButtonMouseClicked
        if (opDepositRadioButton.isSelected()){
            deposit();
        }
        else if(opRetireRadioButton.isSelected()){
            retire();
        }
        else if(opConsultAccountBalanceRadioButton.isSelected()){
            showAccountDetails();
        }
        cleanTextFields();
    }//GEN-LAST:event_opButtonMouseClicked

    private void showUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUsersMouseClicked
        this.showAccounts();
    }//GEN-LAST:event_showUsersMouseClicked

    private void addAccount(){
        accounts.add(c, new User(addDpiTextField.getText(), addNameTextField.getText(), addBalanceTextField.getText()));
        cleanTextFields();
        c++;
    }
    
    private void deposit(){
        if(!opDpiTextField.getText().isEmpty() && !opAmountTextField.getText().isEmpty())
        {
            Boolean isPresent = false, operationPerformed = false;
            int accountIdx = -1;
            for ( int i = 0; i < c; i++ ){
                if ( accounts.get(i).getDpi().equals(opDpiTextField.getText())){
                    operationPerformed = accounts.get(i).deposit(opAmountTextField.getText());
                    isPresent = true;
                    accountIdx = i;
                    break;
                }
            }
            if(!isPresent){
                JOptionPane.showMessageDialog(rootPane, "No tiene una cuenta en este Banco");
            }
            
            if (operationPerformed) {
                JOptionPane.showMessageDialog(rootPane, "Operacion Realizada con Exito\n"+ accounts.get(accountIdx).getName()
                        + "Saldo actual: " + accounts.get(accountIdx).getBalance());
            }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "No introdujo bien los datos");
        }
    }
    
    private void retire(){
        if(!opDpiTextField.getText().isEmpty() && !opAmountTextField.getText().isEmpty())
        {
            Boolean isPresent = false, operationPerformed = false;
            int accountIdx = -1;
            for ( int i = 0; i < c; i++ ){
                if ( accounts.get(i).getDpi().equals(opDpiTextField.getText())){
                    operationPerformed = accounts.get(i).retire(opAmountTextField.getText());
                    isPresent = true;
                    accountIdx = i;
                    break;
                }
            }
            if(!isPresent){
                JOptionPane.showMessageDialog(rootPane, "No tiene una cuenta en este Banco");
            }
            
            if (operationPerformed){
                JOptionPane.showMessageDialog(rootPane, "Operacion Realizada con Exito\n"+ accounts.get(accountIdx).getName()
                        + "Saldo actual: " + accounts.get(accountIdx).getBalance());
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "No cuenta con fondos suficientes");
            }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "No introdujo bien los datos");
        }
    }
    
    private void showAccounts()
    {
        String accountsAsString = "";
        for ( int i = 0; i < c; i++ )
        {
            accountsAsString = accountsAsString.concat(accounts.get(i).getAccountData());
        }
        JOptionPane.showMessageDialog(rootPane, accountsAsString);
    }
    
    private void showAccountDetails(){
        if ( !opDpiTextField.getText().isEmpty() ){
            Boolean isPresent = false;
            int idx = -1;
            for ( int i = 0; i < c; i++ ){
                if( opDpiTextField.getText().equals(accounts.get(i).getDpi())){
                    idx = i;
                    isPresent = true;
                    break;
                }
            }
            if (isPresent){
                JOptionPane.showMessageDialog(rootPane, accounts.get(idx).getAccountData());
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "No tiene una cuenta con nosotros");
            }
        }
    }
    
    private void cleanTextFields(){
        addDpiTextField.setText("");
        addNameTextField.setText("");
        addBalanceTextField.setText("");
        opDpiTextField.setText("");
        opAmountTextField.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addBalanceTextField;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addDpiTextField;
    private javax.swing.JTextField addNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField opAmountTextField;
    private javax.swing.JButton opButton;
    private javax.swing.JRadioButton opConsultAccountBalanceRadioButton;
    private javax.swing.JRadioButton opDepositRadioButton;
    private javax.swing.JTextField opDpiTextField;
    private javax.swing.JRadioButton opRetireRadioButton;
    private javax.swing.JButton showUsers;
    // End of variables declaration//GEN-END:variables
}
